"""Assemble workflow_definition.ts from the 7 Code node JS snippets.

Reads:
  01_verify_hmac.js, 02_odoo_client.js, 03_..., ..., 07_log_row.js

Writes:
  workflow_definition.ts — self-contained TypeScript using @n8n/workflow-sdk
  that can be passed to mcp__claude_ai_n8n__create_workflow_from_code.

The Odoo client helper (02_) is prepended to snippets 03, 04, 05, 06 which
need odooExecute(). Snippets 01 and 07 don't need it.
"""
from pathlib import Path

HERE = Path(__file__).parent

SNIPPETS = {
    "hmac": HERE / "01_verify_hmac.js",
    "odoo_client": HERE / "02_odoo_client.js",
    "partner": HERE / "03_find_or_create_partner.js",
    "products": HERE / "04_match_products.js",
    "sale_order": HERE / "05_create_sale_order.js",
    "activity": HERE / "06_activity_on_picking.js",
    "log": HERE / "07_log_row.js",
}


def escape_for_template_literal(js: str) -> str:
    """Escape a JS string so it can be embedded in a TS template literal.

    Replaces backticks with \\` and ${ with \\${ so they are preserved literally
    when the outer template literal is evaluated.
    """
    return js.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${")


def build_ts() -> str:
    parts = {k: v.read_text(encoding="utf-8") for k, v in SNIPPETS.items()}

    # Snippets that need Odoo client helper prepended
    odoo_client_js = parts["odoo_client"]
    with_odoo = {
        "partner": odoo_client_js + "\n\n" + parts["partner"],
        "products": odoo_client_js + "\n\n" + parts["products"],
        "sale_order": odoo_client_js + "\n\n" + parts["sale_order"],
        "activity": odoo_client_js + "\n\n" + parts["activity"],
    }

    def block(js: str) -> str:
        return escape_for_template_literal(js)

    ts = f"""// MY.LAB - Shopify → Commande Odoo workflow definition
// Generated by scripts/n8n/shopify_order_workflow/build_workflow.py
// Do not edit directly — edit the .js snippets and rerun the builder.

import {{ workflow, node, trigger }} from '@n8n/workflow-sdk';

const HMAC_JS = `{block(parts['hmac'])}`;

const PARTNER_JS = `{block(with_odoo['partner'])}`;

const PRODUCTS_JS = `{block(with_odoo['products'])}`;

const SALE_ORDER_JS = `{block(with_odoo['sale_order'])}`;

const ACTIVITY_JS = `{block(with_odoo['activity'])}`;

const LOG_ROW_JS = `{block(parts['log'])}`;

const webhookNode = trigger({{
  type: 'n8n-nodes-base.webhook',
  version: 2.1,
  config: {{
    name: 'Webhook Shopify',
    position: [240, 300],
    parameters: {{
      path: 'mylab-shopify-order',
      httpMethod: 'POST',
      responseMode: 'onReceived',
      options: {{ rawBody: true }},
    }},
  }},
}});

const verifyHmacNode = node({{
  type: 'n8n-nodes-base.code',
  version: 2,
  config: {{
    name: 'Verify HMAC',
    position: [460, 300],
    parameters: {{
      mode: 'runOnceForAllItems',
      language: 'javaScript',
      jsCode: HMAC_JS,
    }},
  }},
}});

const partnerNode = node({{
  type: 'n8n-nodes-base.code',
  version: 2,
  config: {{
    name: 'Find/Create Partner',
    position: [680, 300],
    parameters: {{
      mode: 'runOnceForAllItems',
      language: 'javaScript',
      jsCode: PARTNER_JS,
    }},
  }},
}});

const productsNode = node({{
  type: 'n8n-nodes-base.code',
  version: 2,
  config: {{
    name: 'Match Products',
    position: [900, 300],
    parameters: {{
      mode: 'runOnceForAllItems',
      language: 'javaScript',
      jsCode: PRODUCTS_JS,
    }},
  }},
}});

const saleOrderNode = node({{
  type: 'n8n-nodes-base.code',
  version: 2,
  config: {{
    name: 'Create Sale Order',
    position: [1120, 300],
    parameters: {{
      mode: 'runOnceForAllItems',
      language: 'javaScript',
      jsCode: SALE_ORDER_JS,
    }},
  }},
}});

const activityNode = node({{
  type: 'n8n-nodes-base.code',
  version: 2,
  config: {{
    name: 'Activity on Picking',
    position: [1340, 300],
    parameters: {{
      mode: 'runOnceForAllItems',
      language: 'javaScript',
      jsCode: ACTIVITY_JS,
    }},
  }},
}});

const logRowNode = node({{
  type: 'n8n-nodes-base.code',
  version: 2,
  config: {{
    name: 'Format Log Row',
    position: [1560, 300],
    parameters: {{
      mode: 'runOnceForAllItems',
      language: 'javaScript',
      jsCode: LOG_ROW_JS,
    }},
  }},
}});

export default workflow('mylab-shopify-order', 'MY.LAB - Shopify → Commande Odoo')
  .add(webhookNode)
  .to(verifyHmacNode)
  .to(partnerNode)
  .to(productsNode)
  .to(saleOrderNode)
  .to(activityNode)
  .to(logRowNode);
"""
    return ts


def main():
    ts = build_ts()
    out = HERE / "workflow_definition.ts"
    out.write_text(ts, encoding="utf-8")
    print(f"Wrote {out} ({len(ts)} chars)")


if __name__ == "__main__":
    main()
