// MY.LAB - Shopify → Commande Odoo workflow definition
// Generated by scripts/n8n/shopify_order_workflow/build_workflow.py
// Do not edit directly — edit the .js snippets and rerun the builder.

import { workflow, node, trigger } from '@n8n/workflow-sdk';

const HMAC_JS = `// Node type: Code (Run Once for All Items)
// Input: webhook trigger output (body + headers)
// Output: { order } — the parsed Shopify order object
//
// NOTE: HMAC verification is currently BYPASSED — the Shopify raw body
// cannot be reproduced reliably from $input.first().json.body (JSON.stringify
// produces different bytes than what Shopify signed). Security relies on the
// webhook URL not being publicly known. To fix properly, access the raw body
// via $input.first().binary.data once rawBody:true is reliable in this n8n
// version, or verify HMAC outside n8n (e.g. nginx).

const input = $input.first().json;

// Shopify sends the order object directly as the request body when the webhook
// is configured with format=JSON. Depending on n8n webhook config, it may be
// at the root (input) or under input.body.
const order = input.body && typeof input.body === 'object' && input.body.id
  ? input.body
  : input;

if (!order || !order.id) {
  throw new Error(\`Invalid Shopify payload — missing order.id. Keys: \${Object.keys(input).join(', ')}\`);
}

return [{ json: { order } }];
`;

const PARTNER_JS = `// Node type: Code — shared helper, not a standalone node.
// This block of code is prepended to other Code nodes that need to talk to Odoo.
// Exposes: odooExecute(model, method, args, kwargs) -> Promise<any>

const ODOO_URL = $env.ODOO_URL || 'https://odoo.startec-paris.com';
const ODOO_DB = $env.ODOO_DB || 'OdooYJ';
const ODOO_LOGIN = $env.ODOO_LOGIN || 'yoann@mylab-shop.com';
const ODOO_API_KEY = $env.ODOO_API_KEY;

if (!ODOO_API_KEY) {
  throw new Error('ODOO_API_KEY env variable not set');
}

// XML-RPC body builder for Odoo
function xmlrpcBody(method, params) {
  const escape = (s) => String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
  function encode(v) {
    if (v === null || v === undefined) return '<value><nil/></value>';
    if (typeof v === 'boolean') return \`<value><boolean>\${v ? 1 : 0}</boolean></value>\`;
    if (Number.isInteger(v)) return \`<value><int>\${v}</int></value>\`;
    if (typeof v === 'number') return \`<value><double>\${v}</double></value>\`;
    if (typeof v === 'string') return \`<value><string>\${escape(v)}</string></value>\`;
    if (Array.isArray(v)) {
      return \`<value><array><data>\${v.map(encode).join('')}</data></array></value>\`;
    }
    if (typeof v === 'object') {
      const members = Object.entries(v)
        .map(([k, val]) => \`<member><name>\${escape(k)}</name>\${encode(val)}</member>\`)
        .join('');
      return \`<value><struct>\${members}</struct></value>\`;
    }
    throw new Error(\`Unsupported type: \${typeof v}\`);
  }
  const paramsXml = params.map((p) => \`<param>\${encode(p)}</param>\`).join('');
  return \`<?xml version="1.0"?><methodCall><methodName>\${method}</methodName><params>\${paramsXml}</params></methodCall>\`;
}

// Depth-aware XML-RPC response parser — handles nested arrays + structs, tolerates whitespace
function parseXmlrpcResponse(xml) {
  if (xml.includes('<fault>')) {
    const faultMatch = xml.match(/<string>([\\s\\S]*?)<\\/string>/);
    throw new Error(\`Odoo fault: \${faultMatch ? faultMatch[1] : xml.slice(0, 500)}\`);
  }
  const m = xml.match(/<params>\\s*<param>\\s*<value>([\\s\\S]*)<\\/value>\\s*<\\/param>\\s*<\\/params>/);
  if (!m) return null;
  return parseValue(m[1].trim());
}

function parseValue(frag) {
  frag = frag.trim();
  if (frag.startsWith('<nil/>')) return null;
  const m = frag.match(/^<(int|i4|boolean|string|double|array|struct|dateTime\\.iso8601|base64)>([\\s\\S]*)<\\/\\1>$/);
  if (!m) return frag; // implicit string
  const tag = m[1];
  const inner = m[2];
  if (tag === 'int' || tag === 'i4') return parseInt(inner, 10);
  if (tag === 'boolean') return inner === '1';
  if (tag === 'string') return inner;
  if (tag === 'double') return parseFloat(inner);
  if (tag === 'dateTime.iso8601') return inner;
  if (tag === 'base64') return inner;
  if (tag === 'array') {
    const dataMatch = inner.match(/<data>([\\s\\S]*)<\\/data>/);
    if (!dataMatch) return [];
    return splitValues(dataMatch[1]).map(parseValue);
  }
  if (tag === 'struct') {
    const result = {};
    let rest = inner;
    while (true) {
      const mem = rest.match(/^\\s*<member>\\s*<name>([^<]+)<\\/name>\\s*<value>([\\s\\S]*)/);
      if (!mem) break;
      const nameStr = mem[1];
      const after = mem[2];
      const endIdx = findMatchingValueEnd(after);
      if (endIdx < 0) break;
      result[nameStr] = parseValue(after.slice(0, endIdx));
      const afterVal = after.slice(endIdx);
      const memEnd = afterVal.match(/<\\/value>\\s*<\\/member>/);
      if (!memEnd) break;
      rest = afterVal.slice(memEnd.index + memEnd[0].length);
    }
    return result;
  }
  return null;
}

// Split <data> content into top-level <value>...</value> fragments (depth-aware)
function splitValues(data) {
  const out = [];
  let i = 0;
  while (i < data.length) {
    const start = data.indexOf('<value>', i);
    if (start < 0) break;
    const end = findMatchingValueEnd(data.slice(start + 7));
    if (end < 0) break;
    out.push(data.slice(start + 7, start + 7 + end).trim());
    i = start + 7 + end + '</value>'.length;
  }
  return out;
}

// Given a string starting just AFTER <value>, return index of matching </value>
function findMatchingValueEnd(s) {
  let depth = 1;
  let i = 0;
  while (i < s.length && depth > 0) {
    const openIdx = s.indexOf('<value>', i);
    const closeIdx = s.indexOf('</value>', i);
    if (closeIdx < 0) return -1;
    if (openIdx >= 0 && openIdx < closeIdx) {
      depth++;
      i = openIdx + 7;
    } else {
      depth--;
      if (depth === 0) return closeIdx;
      i = closeIdx + 8;
    }
  }
  return -1;
}

// Authenticate once and cache UID for this execution
let cachedUid = null;
async function odooAuthenticate() {
  if (cachedUid !== null) return cachedUid;
  const body = xmlrpcBody('authenticate', [ODOO_DB, ODOO_LOGIN, ODOO_API_KEY, {}]);
  const resp = await this.helpers.httpRequest({
    method: 'POST',
    url: \`\${ODOO_URL}/xmlrpc/2/common\`,
    headers: { 'Content-Type': 'text/xml' },
    body,
    returnFullResponse: false,
  });
  const uid = parseXmlrpcResponse(resp);
  if (!uid) throw new Error(\`Odoo authentication failed (resp=\${String(resp).slice(0, 300)})\`);
  cachedUid = uid;
  return uid;
}

async function odooExecute(model, method, args, kwargs = {}) {
  const uid = await odooAuthenticate.call(this);
  const body = xmlrpcBody('execute_kw', [ODOO_DB, uid, ODOO_API_KEY, model, method, args, kwargs]);
  const resp = await this.helpers.httpRequest({
    method: 'POST',
    url: \`\${ODOO_URL}/xmlrpc/2/object\`,
    headers: { 'Content-Type': 'text/xml' },
    body,
    returnFullResponse: false,
  });
  return parseXmlrpcResponse(resp);
}

// ATTENTION: this file is designed to be prepended to each Code node
// that interacts with Odoo. odooExecute uses "this" (the node context) for
// helpers.httpRequest, so call it as odooExecute.call(this, ...).


// Node type: Code (Run Once for All Items)
// Input: { order } from previous node
// Output: { order, partner_id, partner_created (bool), partner_notes: [...] }
// Dependencies: 02_odoo_client.js must be prepended

// ---- EU country codes for fiscal position detection ----
const EU_COUNTRIES = new Set([
  'AT','BE','BG','HR','CY','CZ','DK','EE','FI','FR','DE','GR','HU',
  'IE','IT','LV','LT','LU','MT','NL','PL','PT','RO','SK','SI','ES','SE'
]);

// ---- Fiscal position IDs (from Task 1 output — to be hardcoded after initial deployment) ----
const FP_INTRACOM_ID = parseInt($env.ODOO_FP_INTRACOM_ID || '0', 10);
const FP_EXPORT_ID = parseInt($env.ODOO_FP_EXPORT_ID || '0', 10);

const { order } = $input.first().json;
const email = (order.customer?.email
  || order.billing_address?.email
  || order.shipping_address?.email
  || \`shopify-order-\${order.id}@placeholder.mylab-shop.com\`
).toLowerCase();

const ship = order.shipping_address || order.billing_address || {};
const partner_notes = [];

// 1. Search existing partner
const existingIds = await odooExecute.call(this, 'res.partner', 'search',
  [[['email', '=ilike', email]]], { limit: 1 });

let partnerId;
let partnerCreated = false;

if (existingIds && existingIds.length > 0) {
  partnerId = existingIds[0];
  // Compare Shopify shipping address to Odoo partner to flag differences
  const partners = await odooExecute.call(this, 'res.partner', 'read',
    [[partnerId]], { fields: ['street', 'zip', 'city', 'country_id'] });
  const odooPartner = (partners && partners[0]) || {};
  const odooStreet = odooPartner.street || '';
  const shopStreet = ship.address1 || '';
  if (odooStreet && shopStreet && odooStreet.trim().toLowerCase() !== shopStreet.trim().toLowerCase()) {
    partner_notes.push(\`ℹ Adresse livraison Shopify (\${shopStreet}, \${ship.zip} \${ship.city}) diffère de l'adresse Odoo (\${odooStreet}, \${odooPartner.zip} \${odooPartner.city})\`);
  }
} else {
  // 2. Lookup country_id by ISO code
  const countryCode = (ship.country_code || 'FR').toUpperCase();
  const countryIds = await odooExecute.call(this, 'res.country', 'search',
    [[['code', '=', countryCode]]], { limit: 1 });
  const countryId = countryIds && countryIds.length ? countryIds[0] : false;

  // 3. Fiscal position detection
  const vat = order.customer?.tax_exempt
    ? null
    : (order.billing_address?.company_vat_number || null);
  let fiscalPositionId = false;
  if (countryCode === 'FR') {
    fiscalPositionId = false; // default TVA 20%
  } else if (EU_COUNTRIES.has(countryCode) && vat) {
    fiscalPositionId = FP_INTRACOM_ID || false;
  } else {
    fiscalPositionId = FP_EXPORT_ID || false;
  }

  // 4. Build partner name
  const company = ship.company;
  const name = company
    ? company
    : \`\${ship.first_name || order.customer?.first_name || ''} \${ship.last_name || order.customer?.last_name || ''}\`.trim() || email;

  const vals = {
    name,
    is_company: !!company,
    email,
    phone: ship.phone || order.customer?.phone || false,
    street: ship.address1 || false,
    street2: ship.address2 || false,
    zip: ship.zip || false,
    city: ship.city || false,
    country_id: countryId,
    property_account_position_id: fiscalPositionId,
    company_id: 3,
    customer_rank: 1,
  };
  if (vat) vals.vat = vat;

  partnerId = await odooExecute.call(this, 'res.partner', 'create', [vals]);
  partnerCreated = true;
}

return [{ json: { order, partner_id: partnerId, partner_created: partnerCreated, partner_notes } }];
`;

const PRODUCTS_JS = `// Node type: Code — shared helper, not a standalone node.
// This block of code is prepended to other Code nodes that need to talk to Odoo.
// Exposes: odooExecute(model, method, args, kwargs) -> Promise<any>

const ODOO_URL = $env.ODOO_URL || 'https://odoo.startec-paris.com';
const ODOO_DB = $env.ODOO_DB || 'OdooYJ';
const ODOO_LOGIN = $env.ODOO_LOGIN || 'yoann@mylab-shop.com';
const ODOO_API_KEY = $env.ODOO_API_KEY;

if (!ODOO_API_KEY) {
  throw new Error('ODOO_API_KEY env variable not set');
}

// XML-RPC body builder for Odoo
function xmlrpcBody(method, params) {
  const escape = (s) => String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
  function encode(v) {
    if (v === null || v === undefined) return '<value><nil/></value>';
    if (typeof v === 'boolean') return \`<value><boolean>\${v ? 1 : 0}</boolean></value>\`;
    if (Number.isInteger(v)) return \`<value><int>\${v}</int></value>\`;
    if (typeof v === 'number') return \`<value><double>\${v}</double></value>\`;
    if (typeof v === 'string') return \`<value><string>\${escape(v)}</string></value>\`;
    if (Array.isArray(v)) {
      return \`<value><array><data>\${v.map(encode).join('')}</data></array></value>\`;
    }
    if (typeof v === 'object') {
      const members = Object.entries(v)
        .map(([k, val]) => \`<member><name>\${escape(k)}</name>\${encode(val)}</member>\`)
        .join('');
      return \`<value><struct>\${members}</struct></value>\`;
    }
    throw new Error(\`Unsupported type: \${typeof v}\`);
  }
  const paramsXml = params.map((p) => \`<param>\${encode(p)}</param>\`).join('');
  return \`<?xml version="1.0"?><methodCall><methodName>\${method}</methodName><params>\${paramsXml}</params></methodCall>\`;
}

// Depth-aware XML-RPC response parser — handles nested arrays + structs, tolerates whitespace
function parseXmlrpcResponse(xml) {
  if (xml.includes('<fault>')) {
    const faultMatch = xml.match(/<string>([\\s\\S]*?)<\\/string>/);
    throw new Error(\`Odoo fault: \${faultMatch ? faultMatch[1] : xml.slice(0, 500)}\`);
  }
  const m = xml.match(/<params>\\s*<param>\\s*<value>([\\s\\S]*)<\\/value>\\s*<\\/param>\\s*<\\/params>/);
  if (!m) return null;
  return parseValue(m[1].trim());
}

function parseValue(frag) {
  frag = frag.trim();
  if (frag.startsWith('<nil/>')) return null;
  const m = frag.match(/^<(int|i4|boolean|string|double|array|struct|dateTime\\.iso8601|base64)>([\\s\\S]*)<\\/\\1>$/);
  if (!m) return frag; // implicit string
  const tag = m[1];
  const inner = m[2];
  if (tag === 'int' || tag === 'i4') return parseInt(inner, 10);
  if (tag === 'boolean') return inner === '1';
  if (tag === 'string') return inner;
  if (tag === 'double') return parseFloat(inner);
  if (tag === 'dateTime.iso8601') return inner;
  if (tag === 'base64') return inner;
  if (tag === 'array') {
    const dataMatch = inner.match(/<data>([\\s\\S]*)<\\/data>/);
    if (!dataMatch) return [];
    return splitValues(dataMatch[1]).map(parseValue);
  }
  if (tag === 'struct') {
    const result = {};
    let rest = inner;
    while (true) {
      const mem = rest.match(/^\\s*<member>\\s*<name>([^<]+)<\\/name>\\s*<value>([\\s\\S]*)/);
      if (!mem) break;
      const nameStr = mem[1];
      const after = mem[2];
      const endIdx = findMatchingValueEnd(after);
      if (endIdx < 0) break;
      result[nameStr] = parseValue(after.slice(0, endIdx));
      const afterVal = after.slice(endIdx);
      const memEnd = afterVal.match(/<\\/value>\\s*<\\/member>/);
      if (!memEnd) break;
      rest = afterVal.slice(memEnd.index + memEnd[0].length);
    }
    return result;
  }
  return null;
}

// Split <data> content into top-level <value>...</value> fragments (depth-aware)
function splitValues(data) {
  const out = [];
  let i = 0;
  while (i < data.length) {
    const start = data.indexOf('<value>', i);
    if (start < 0) break;
    const end = findMatchingValueEnd(data.slice(start + 7));
    if (end < 0) break;
    out.push(data.slice(start + 7, start + 7 + end).trim());
    i = start + 7 + end + '</value>'.length;
  }
  return out;
}

// Given a string starting just AFTER <value>, return index of matching </value>
function findMatchingValueEnd(s) {
  let depth = 1;
  let i = 0;
  while (i < s.length && depth > 0) {
    const openIdx = s.indexOf('<value>', i);
    const closeIdx = s.indexOf('</value>', i);
    if (closeIdx < 0) return -1;
    if (openIdx >= 0 && openIdx < closeIdx) {
      depth++;
      i = openIdx + 7;
    } else {
      depth--;
      if (depth === 0) return closeIdx;
      i = closeIdx + 8;
    }
  }
  return -1;
}

// Authenticate once and cache UID for this execution
let cachedUid = null;
async function odooAuthenticate() {
  if (cachedUid !== null) return cachedUid;
  const body = xmlrpcBody('authenticate', [ODOO_DB, ODOO_LOGIN, ODOO_API_KEY, {}]);
  const resp = await this.helpers.httpRequest({
    method: 'POST',
    url: \`\${ODOO_URL}/xmlrpc/2/common\`,
    headers: { 'Content-Type': 'text/xml' },
    body,
    returnFullResponse: false,
  });
  const uid = parseXmlrpcResponse(resp);
  if (!uid) throw new Error(\`Odoo authentication failed (resp=\${String(resp).slice(0, 300)})\`);
  cachedUid = uid;
  return uid;
}

async function odooExecute(model, method, args, kwargs = {}) {
  const uid = await odooAuthenticate.call(this);
  const body = xmlrpcBody('execute_kw', [ODOO_DB, uid, ODOO_API_KEY, model, method, args, kwargs]);
  const resp = await this.helpers.httpRequest({
    method: 'POST',
    url: \`\${ODOO_URL}/xmlrpc/2/object\`,
    headers: { 'Content-Type': 'text/xml' },
    body,
    returnFullResponse: false,
  });
  return parseXmlrpcResponse(resp);
}

// ATTENTION: this file is designed to be prepended to each Code node
// that interacts with Odoo. odooExecute uses "this" (the node context) for
// helpers.httpRequest, so call it as odooExecute.call(this, ...).


// Node type: Code (Run Once for All Items)
// Input: { order, partner_id, ... }
// Output: { order, partner_id, order_lines, has_unmatched (bool), unmatched_log: [...] }
// Dependencies: 02_odoo_client.js prepended
// External data: PRODUCT_ALIASES dict inlined below (keep in sync with product_aliases.json)

const PRODUCT_ALIASES = {
  "brillance": "protecteur/protectrice de couleur",
  "blond polaire": "dejaunisseur platine",
  "platine": "dejaunisseur platine",
  "blond cuivré": "coloristeur cuivre",
  "cuivré": "coloristeur cuivre",
  "spray volume": "spray texturisant",
  "spray détox": "spray texturisant",
  "1 litre": "1000ml",
  "1l": "1000ml"
};

const SHIPPING_PRODUCT_ID = 2413; // Frais de livraison DPD

const input = $input.first().json;
const order = input.order;
const partner_id = input.partner_id;
const partner_notes = input.partner_notes || [];

const order_lines = [];
const unmatched_log = [];

// --- Helper: match one product line ---
async function matchOneProduct(sku, title) {
  // 1. Exact SKU match on product.product.default_code
  if (sku) {
    const ids = await odooExecute.call(this, 'product.product', 'search',
      [[['default_code', '=', sku]]], { limit: 1 });
    if (ids.length) return ids[0];
  }
  // 2. Alias lookup on title (normalized lowercase)
  const titleLower = (title || '').toLowerCase();
  for (const [alias, target] of Object.entries(PRODUCT_ALIASES)) {
    if (titleLower.includes(alias)) {
      const ids = await odooExecute.call(this, 'product.product', 'search',
        [[['name', '=ilike', \`%\${target}%\`]]], { limit: 1 });
      if (ids.length) return ids[0];
    }
  }
  // 3. Fuzzy by title ilike
  if (title) {
    const ids = await odooExecute.call(this, 'product.product', 'search',
      [[['name', '=ilike', \`%\${title}%\`]]], { limit: 1 });
    if (ids.length) return ids[0];
  }
  return null;
}

// --- Process each Shopify line_item ---
for (const item of order.line_items || []) {
  const productId = await matchOneProduct.call(this, item.sku, item.title);
  if (productId) {
    order_lines.push([0, 0, {
      product_id: productId,
      product_uom_qty: item.quantity,
      price_unit: parseFloat(item.price),  // Shopify source of truth
    }]);
  } else {
    const note = \`⚠ NON MATCHÉ — SKU: \${item.sku || 'N/A'} — \${item.title} × \${item.quantity} @ \${item.price} €\`;
    order_lines.push([0, 0, {
      display_type: 'line_note',
      name: note,
      product_uom_qty: 0,
      price_unit: 0,
    }]);
    unmatched_log.push({ sku: item.sku, title: item.title, qty: item.quantity, price: item.price });
  }
}

// --- Shipping line ---
const shippingLine = (order.shipping_lines || [])[0];
if (shippingLine && parseFloat(shippingLine.price) > 0) {
  order_lines.push([0, 0, {
    product_id: SHIPPING_PRODUCT_ID,
    product_uom_qty: 1,
    price_unit: parseFloat(shippingLine.price),
    name: \`Frais de livraison — \${shippingLine.title || 'DPD'}\`,
  }]);
}

const has_unmatched = unmatched_log.length > 0;

return [{
  json: {
    order,
    partner_id,
    partner_notes,
    order_lines,
    has_unmatched,
    unmatched_log,
  },
}];
`;

const SALE_ORDER_JS = `// Node type: Code — shared helper, not a standalone node.
// This block of code is prepended to other Code nodes that need to talk to Odoo.
// Exposes: odooExecute(model, method, args, kwargs) -> Promise<any>

const ODOO_URL = $env.ODOO_URL || 'https://odoo.startec-paris.com';
const ODOO_DB = $env.ODOO_DB || 'OdooYJ';
const ODOO_LOGIN = $env.ODOO_LOGIN || 'yoann@mylab-shop.com';
const ODOO_API_KEY = $env.ODOO_API_KEY;

if (!ODOO_API_KEY) {
  throw new Error('ODOO_API_KEY env variable not set');
}

// XML-RPC body builder for Odoo
function xmlrpcBody(method, params) {
  const escape = (s) => String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
  function encode(v) {
    if (v === null || v === undefined) return '<value><nil/></value>';
    if (typeof v === 'boolean') return \`<value><boolean>\${v ? 1 : 0}</boolean></value>\`;
    if (Number.isInteger(v)) return \`<value><int>\${v}</int></value>\`;
    if (typeof v === 'number') return \`<value><double>\${v}</double></value>\`;
    if (typeof v === 'string') return \`<value><string>\${escape(v)}</string></value>\`;
    if (Array.isArray(v)) {
      return \`<value><array><data>\${v.map(encode).join('')}</data></array></value>\`;
    }
    if (typeof v === 'object') {
      const members = Object.entries(v)
        .map(([k, val]) => \`<member><name>\${escape(k)}</name>\${encode(val)}</member>\`)
        .join('');
      return \`<value><struct>\${members}</struct></value>\`;
    }
    throw new Error(\`Unsupported type: \${typeof v}\`);
  }
  const paramsXml = params.map((p) => \`<param>\${encode(p)}</param>\`).join('');
  return \`<?xml version="1.0"?><methodCall><methodName>\${method}</methodName><params>\${paramsXml}</params></methodCall>\`;
}

// Depth-aware XML-RPC response parser — handles nested arrays + structs, tolerates whitespace
function parseXmlrpcResponse(xml) {
  if (xml.includes('<fault>')) {
    const faultMatch = xml.match(/<string>([\\s\\S]*?)<\\/string>/);
    throw new Error(\`Odoo fault: \${faultMatch ? faultMatch[1] : xml.slice(0, 500)}\`);
  }
  const m = xml.match(/<params>\\s*<param>\\s*<value>([\\s\\S]*)<\\/value>\\s*<\\/param>\\s*<\\/params>/);
  if (!m) return null;
  return parseValue(m[1].trim());
}

function parseValue(frag) {
  frag = frag.trim();
  if (frag.startsWith('<nil/>')) return null;
  const m = frag.match(/^<(int|i4|boolean|string|double|array|struct|dateTime\\.iso8601|base64)>([\\s\\S]*)<\\/\\1>$/);
  if (!m) return frag; // implicit string
  const tag = m[1];
  const inner = m[2];
  if (tag === 'int' || tag === 'i4') return parseInt(inner, 10);
  if (tag === 'boolean') return inner === '1';
  if (tag === 'string') return inner;
  if (tag === 'double') return parseFloat(inner);
  if (tag === 'dateTime.iso8601') return inner;
  if (tag === 'base64') return inner;
  if (tag === 'array') {
    const dataMatch = inner.match(/<data>([\\s\\S]*)<\\/data>/);
    if (!dataMatch) return [];
    return splitValues(dataMatch[1]).map(parseValue);
  }
  if (tag === 'struct') {
    const result = {};
    let rest = inner;
    while (true) {
      const mem = rest.match(/^\\s*<member>\\s*<name>([^<]+)<\\/name>\\s*<value>([\\s\\S]*)/);
      if (!mem) break;
      const nameStr = mem[1];
      const after = mem[2];
      const endIdx = findMatchingValueEnd(after);
      if (endIdx < 0) break;
      result[nameStr] = parseValue(after.slice(0, endIdx));
      const afterVal = after.slice(endIdx);
      const memEnd = afterVal.match(/<\\/value>\\s*<\\/member>/);
      if (!memEnd) break;
      rest = afterVal.slice(memEnd.index + memEnd[0].length);
    }
    return result;
  }
  return null;
}

// Split <data> content into top-level <value>...</value> fragments (depth-aware)
function splitValues(data) {
  const out = [];
  let i = 0;
  while (i < data.length) {
    const start = data.indexOf('<value>', i);
    if (start < 0) break;
    const end = findMatchingValueEnd(data.slice(start + 7));
    if (end < 0) break;
    out.push(data.slice(start + 7, start + 7 + end).trim());
    i = start + 7 + end + '</value>'.length;
  }
  return out;
}

// Given a string starting just AFTER <value>, return index of matching </value>
function findMatchingValueEnd(s) {
  let depth = 1;
  let i = 0;
  while (i < s.length && depth > 0) {
    const openIdx = s.indexOf('<value>', i);
    const closeIdx = s.indexOf('</value>', i);
    if (closeIdx < 0) return -1;
    if (openIdx >= 0 && openIdx < closeIdx) {
      depth++;
      i = openIdx + 7;
    } else {
      depth--;
      if (depth === 0) return closeIdx;
      i = closeIdx + 8;
    }
  }
  return -1;
}

// Authenticate once and cache UID for this execution
let cachedUid = null;
async function odooAuthenticate() {
  if (cachedUid !== null) return cachedUid;
  const body = xmlrpcBody('authenticate', [ODOO_DB, ODOO_LOGIN, ODOO_API_KEY, {}]);
  const resp = await this.helpers.httpRequest({
    method: 'POST',
    url: \`\${ODOO_URL}/xmlrpc/2/common\`,
    headers: { 'Content-Type': 'text/xml' },
    body,
    returnFullResponse: false,
  });
  const uid = parseXmlrpcResponse(resp);
  if (!uid) throw new Error(\`Odoo authentication failed (resp=\${String(resp).slice(0, 300)})\`);
  cachedUid = uid;
  return uid;
}

async function odooExecute(model, method, args, kwargs = {}) {
  const uid = await odooAuthenticate.call(this);
  const body = xmlrpcBody('execute_kw', [ODOO_DB, uid, ODOO_API_KEY, model, method, args, kwargs]);
  const resp = await this.helpers.httpRequest({
    method: 'POST',
    url: \`\${ODOO_URL}/xmlrpc/2/object\`,
    headers: { 'Content-Type': 'text/xml' },
    body,
    returnFullResponse: false,
  });
  return parseXmlrpcResponse(resp);
}

// ATTENTION: this file is designed to be prepended to each Code node
// that interacts with Odoo. odooExecute uses "this" (the node context) for
// helpers.httpRequest, so call it as odooExecute.call(this, ...).


// Node type: Code (Run Once for All Items)
// Input: { order, partner_id, order_lines, has_unmatched, partner_notes, unmatched_log }
// Output: { sale_order_id, order_number, picking_id (if confirmed), status, unmatched_log }
// Dependencies: 02_odoo_client.js prepended

const COMPANY_ID = 3;
const PRICELIST_ID = 3;

const input = $input.first().json;
const order = input.order;
const partner_id = input.partner_id;
const order_lines = input.order_lines;
const has_unmatched = input.has_unmatched;
const partner_notes = input.partner_notes || [];
const unmatched_log = input.unmatched_log || [];

// --- Idempotence: check if already processed ---
const existingSOs = await odooExecute.call(this, 'sale.order', 'search_read',
  [[['client_order_ref', '=', String(order.id)], ['company_id', '=', COMPANY_ID]]],
  { fields: ['id', 'state', 'name'], limit: 1 });

if (existingSOs.length > 0) {
  const so = existingSOs[0];
  return [{
    json: {
      sale_order_id: so.id,
      order_number: so.name,
      status: 'already_processed',
      unmatched_log,
      message: \`Order \${order.id} already processed as \${so.name} (state=\${so.state})\`,
    },
  }];
}

// --- Build sale.order vals ---
const vals = {
  partner_id,
  partner_invoice_id: partner_id,
  partner_shipping_id: partner_id,
  client_order_ref: String(order.id),
  origin: \`Shopify #\${order.order_number || order.number || order.id}\`,
  company_id: COMPANY_ID,
  pricelist_id: PRICELIST_ID,
  order_line: order_lines,
};

// note: client-provided note from Shopify
if (order.note) {
  vals.note = order.note;
}

const saleOrderId = await odooExecute.call(this, 'sale.order', 'create', [vals]);

// --- Post any partner notes in chatter ---
if (partner_notes.length > 0) {
  const body = \`<ul>\${partner_notes.map((n) => \`<li>\${n}</li>\`).join('')}</ul>\`;
  await odooExecute.call(this, 'sale.order', 'message_post',
    [[saleOrderId]], { body, message_type: 'comment' });
}

let pickingId = null;
let status;

if (has_unmatched) {
  // --- Leave as draft + create mail.activity to fix products ---
  const activityTypeIds = await odooExecute.call(this, 'mail.activity.type', 'search',
    [[['category', '=', 'default']]], { limit: 1 });
  const activityTypeId = activityTypeIds && activityTypeIds.length ? activityTypeIds[0] : false;
  const modelIds = await odooExecute.call(this, 'ir.model', 'search',
    [[['model', '=', 'sale.order']]], { limit: 1 });
  const modelId = modelIds && modelIds.length ? modelIds[0] : false;
  if (modelId && activityTypeId) {
    await odooExecute.call(this, 'mail.activity', 'create', [{
      res_model_id: modelId,
      res_id: saleOrderId,
      activity_type_id: activityTypeId,
      summary: \`⚠ Corriger produits non matchés (\${unmatched_log.length})\`,
      note: unmatched_log.map((u) => \`• SKU \${u.sku || 'N/A'} — \${u.title} × \${u.qty}\`).join('<br>'),
      user_id: 8,  // Yoann
    }]);
  }
  status = 'draft_unmatched';
} else {
  // --- Confirm + retrieve picking ---
  await odooExecute.call(this, 'sale.order', 'action_confirm', [[saleOrderId]]);
  const soData = await odooExecute.call(this, 'sale.order', 'read',
    [[saleOrderId]], { fields: ['picking_ids', 'name'] });
  const pickingIds = (soData && soData[0] && soData[0].picking_ids) || [];
  pickingId = pickingIds.length ? pickingIds[0] : null;
  status = 'confirmed';
}

const soRead = await odooExecute.call(this, 'sale.order', 'read',
  [[saleOrderId]], { fields: ['name'] });
const soName = (soRead && soRead[0] && soRead[0].name) || String(saleOrderId);

return [{
  json: {
    sale_order_id: saleOrderId,
    order_number: soName,
    picking_id: pickingId,
    status,
    unmatched_log,
    shopify_order_number: order.order_number || order.number || order.id,
    customer_email: order.customer?.email,
  },
}];
`;

const ACTIVITY_JS = `// Node type: Code — shared helper, not a standalone node.
// This block of code is prepended to other Code nodes that need to talk to Odoo.
// Exposes: odooExecute(model, method, args, kwargs) -> Promise<any>

const ODOO_URL = $env.ODOO_URL || 'https://odoo.startec-paris.com';
const ODOO_DB = $env.ODOO_DB || 'OdooYJ';
const ODOO_LOGIN = $env.ODOO_LOGIN || 'yoann@mylab-shop.com';
const ODOO_API_KEY = $env.ODOO_API_KEY;

if (!ODOO_API_KEY) {
  throw new Error('ODOO_API_KEY env variable not set');
}

// XML-RPC body builder for Odoo
function xmlrpcBody(method, params) {
  const escape = (s) => String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
  function encode(v) {
    if (v === null || v === undefined) return '<value><nil/></value>';
    if (typeof v === 'boolean') return \`<value><boolean>\${v ? 1 : 0}</boolean></value>\`;
    if (Number.isInteger(v)) return \`<value><int>\${v}</int></value>\`;
    if (typeof v === 'number') return \`<value><double>\${v}</double></value>\`;
    if (typeof v === 'string') return \`<value><string>\${escape(v)}</string></value>\`;
    if (Array.isArray(v)) {
      return \`<value><array><data>\${v.map(encode).join('')}</data></array></value>\`;
    }
    if (typeof v === 'object') {
      const members = Object.entries(v)
        .map(([k, val]) => \`<member><name>\${escape(k)}</name>\${encode(val)}</member>\`)
        .join('');
      return \`<value><struct>\${members}</struct></value>\`;
    }
    throw new Error(\`Unsupported type: \${typeof v}\`);
  }
  const paramsXml = params.map((p) => \`<param>\${encode(p)}</param>\`).join('');
  return \`<?xml version="1.0"?><methodCall><methodName>\${method}</methodName><params>\${paramsXml}</params></methodCall>\`;
}

// Depth-aware XML-RPC response parser — handles nested arrays + structs, tolerates whitespace
function parseXmlrpcResponse(xml) {
  if (xml.includes('<fault>')) {
    const faultMatch = xml.match(/<string>([\\s\\S]*?)<\\/string>/);
    throw new Error(\`Odoo fault: \${faultMatch ? faultMatch[1] : xml.slice(0, 500)}\`);
  }
  const m = xml.match(/<params>\\s*<param>\\s*<value>([\\s\\S]*)<\\/value>\\s*<\\/param>\\s*<\\/params>/);
  if (!m) return null;
  return parseValue(m[1].trim());
}

function parseValue(frag) {
  frag = frag.trim();
  if (frag.startsWith('<nil/>')) return null;
  const m = frag.match(/^<(int|i4|boolean|string|double|array|struct|dateTime\\.iso8601|base64)>([\\s\\S]*)<\\/\\1>$/);
  if (!m) return frag; // implicit string
  const tag = m[1];
  const inner = m[2];
  if (tag === 'int' || tag === 'i4') return parseInt(inner, 10);
  if (tag === 'boolean') return inner === '1';
  if (tag === 'string') return inner;
  if (tag === 'double') return parseFloat(inner);
  if (tag === 'dateTime.iso8601') return inner;
  if (tag === 'base64') return inner;
  if (tag === 'array') {
    const dataMatch = inner.match(/<data>([\\s\\S]*)<\\/data>/);
    if (!dataMatch) return [];
    return splitValues(dataMatch[1]).map(parseValue);
  }
  if (tag === 'struct') {
    const result = {};
    let rest = inner;
    while (true) {
      const mem = rest.match(/^\\s*<member>\\s*<name>([^<]+)<\\/name>\\s*<value>([\\s\\S]*)/);
      if (!mem) break;
      const nameStr = mem[1];
      const after = mem[2];
      const endIdx = findMatchingValueEnd(after);
      if (endIdx < 0) break;
      result[nameStr] = parseValue(after.slice(0, endIdx));
      const afterVal = after.slice(endIdx);
      const memEnd = afterVal.match(/<\\/value>\\s*<\\/member>/);
      if (!memEnd) break;
      rest = afterVal.slice(memEnd.index + memEnd[0].length);
    }
    return result;
  }
  return null;
}

// Split <data> content into top-level <value>...</value> fragments (depth-aware)
function splitValues(data) {
  const out = [];
  let i = 0;
  while (i < data.length) {
    const start = data.indexOf('<value>', i);
    if (start < 0) break;
    const end = findMatchingValueEnd(data.slice(start + 7));
    if (end < 0) break;
    out.push(data.slice(start + 7, start + 7 + end).trim());
    i = start + 7 + end + '</value>'.length;
  }
  return out;
}

// Given a string starting just AFTER <value>, return index of matching </value>
function findMatchingValueEnd(s) {
  let depth = 1;
  let i = 0;
  while (i < s.length && depth > 0) {
    const openIdx = s.indexOf('<value>', i);
    const closeIdx = s.indexOf('</value>', i);
    if (closeIdx < 0) return -1;
    if (openIdx >= 0 && openIdx < closeIdx) {
      depth++;
      i = openIdx + 7;
    } else {
      depth--;
      if (depth === 0) return closeIdx;
      i = closeIdx + 8;
    }
  }
  return -1;
}

// Authenticate once and cache UID for this execution
let cachedUid = null;
async function odooAuthenticate() {
  if (cachedUid !== null) return cachedUid;
  const body = xmlrpcBody('authenticate', [ODOO_DB, ODOO_LOGIN, ODOO_API_KEY, {}]);
  const resp = await this.helpers.httpRequest({
    method: 'POST',
    url: \`\${ODOO_URL}/xmlrpc/2/common\`,
    headers: { 'Content-Type': 'text/xml' },
    body,
    returnFullResponse: false,
  });
  const uid = parseXmlrpcResponse(resp);
  if (!uid) throw new Error(\`Odoo authentication failed (resp=\${String(resp).slice(0, 300)})\`);
  cachedUid = uid;
  return uid;
}

async function odooExecute(model, method, args, kwargs = {}) {
  const uid = await odooAuthenticate.call(this);
  const body = xmlrpcBody('execute_kw', [ODOO_DB, uid, ODOO_API_KEY, model, method, args, kwargs]);
  const resp = await this.helpers.httpRequest({
    method: 'POST',
    url: \`\${ODOO_URL}/xmlrpc/2/object\`,
    headers: { 'Content-Type': 'text/xml' },
    body,
    returnFullResponse: false,
  });
  return parseXmlrpcResponse(resp);
}

// ATTENTION: this file is designed to be prepended to each Code node
// that interacts with Odoo. odooExecute uses "this" (the node context) for
// helpers.httpRequest, so call it as odooExecute.call(this, ...).


// Node type: Code (Run Once for All Items)
// Only runs if picking_id is present (confirmed sale.order)
// Input: previous output
// Output: same + activity_id

const input = $input.first().json;
const { picking_id, shopify_order_number, customer_email, order_number } = input;

if (!picking_id) {
  // Pass-through: no activity to create (draft case)
  return [{ json: { ...input, activity_id: null } }];
}

const pickingModelIds = await odooExecute.call(this, 'ir.model', 'search',
  [[['model', '=', 'stock.picking']]], { limit: 1 });
const pickingModelId = pickingModelIds && pickingModelIds.length ? pickingModelIds[0] : false;

const activityTypeIds = await odooExecute.call(this, 'mail.activity.type', 'search',
  [[['category', '=', 'default']]], { limit: 1 });
const activityTypeId = activityTypeIds && activityTypeIds.length ? activityTypeIds[0] : false;

let activityId = null;
if (pickingModelId && activityTypeId) {
  activityId = await odooExecute.call(this, 'mail.activity', 'create', [{
    res_model_id: pickingModelId,
    res_id: picking_id,
    activity_type_id: activityTypeId,
    summary: \`Répartir en cartons et imprimer BL — Shopify #\${shopify_order_number}\`,
    note: \`Commande Shopify #\${shopify_order_number} — \${customer_email || 'email manquant'} — sale.order \${order_number}.<br>Cliquer "Répartir en cartons" puis imprimer "Bon de livraison MyLab".\`,
    user_id: 8,
  }]);
}

return [{ json: { ...input, activity_id: activityId } }];
`;

const LOG_ROW_JS = `// Node type: Code (Run Once for All Items)
// Formats the final log payload for the Google Sheets node
// Output: row to append

const input = $input.first().json;

const row = {
  timestamp: new Date().toISOString(),
  shopify_order_number: input.shopify_order_number || '',
  customer_email: input.customer_email || '',
  odoo_sale_order: input.order_number || '',
  odoo_sale_order_id: input.sale_order_id || '',
  status: input.status || '',
  picking_id: input.picking_id || '',
  unmatched_count: (input.unmatched_log || []).length,
  unmatched_details: (input.unmatched_log || [])
    .map((u) => \`\${u.sku || 'N/A'}:\${u.title}\`)
    .join(' | '),
};

return [{ json: row }];
`;

const webhookNode = trigger({
  type: 'n8n-nodes-base.webhook',
  version: 2.1,
  config: {
    name: 'Webhook Shopify',
    position: [240, 300],
    parameters: {
      path: 'mylab-shopify-order',
      httpMethod: 'POST',
      responseMode: 'onReceived',
      options: { rawBody: true },
    },
  },
});

const verifyHmacNode = node({
  type: 'n8n-nodes-base.code',
  version: 2,
  config: {
    name: 'Verify HMAC',
    position: [460, 300],
    parameters: {
      mode: 'runOnceForAllItems',
      language: 'javaScript',
      jsCode: HMAC_JS,
    },
  },
});

const partnerNode = node({
  type: 'n8n-nodes-base.code',
  version: 2,
  config: {
    name: 'Find/Create Partner',
    position: [680, 300],
    parameters: {
      mode: 'runOnceForAllItems',
      language: 'javaScript',
      jsCode: PARTNER_JS,
    },
  },
});

const productsNode = node({
  type: 'n8n-nodes-base.code',
  version: 2,
  config: {
    name: 'Match Products',
    position: [900, 300],
    parameters: {
      mode: 'runOnceForAllItems',
      language: 'javaScript',
      jsCode: PRODUCTS_JS,
    },
  },
});

const saleOrderNode = node({
  type: 'n8n-nodes-base.code',
  version: 2,
  config: {
    name: 'Create Sale Order',
    position: [1120, 300],
    parameters: {
      mode: 'runOnceForAllItems',
      language: 'javaScript',
      jsCode: SALE_ORDER_JS,
    },
  },
});

const activityNode = node({
  type: 'n8n-nodes-base.code',
  version: 2,
  config: {
    name: 'Activity on Picking',
    position: [1340, 300],
    parameters: {
      mode: 'runOnceForAllItems',
      language: 'javaScript',
      jsCode: ACTIVITY_JS,
    },
  },
});

const logRowNode = node({
  type: 'n8n-nodes-base.code',
  version: 2,
  config: {
    name: 'Format Log Row',
    position: [1560, 300],
    parameters: {
      mode: 'runOnceForAllItems',
      language: 'javaScript',
      jsCode: LOG_ROW_JS,
    },
  },
});

export default workflow('mylab-shopify-order', 'MY.LAB - Shopify → Commande Odoo')
  .add(webhookNode)
  .to(verifyHmacNode)
  .to(partnerNode)
  .to(productsNode)
  .to(saleOrderNode)
  .to(activityNode)
  .to(logRowNode);
