#!/bin/bash
# MY.LAB — Upload Takemoto bottle images to Shopify Files
# Generated by scrape_takemoto.py
# 63 images to upload

STORE="mylab-shop-3.myshopify.com"

echo "Uploading takemoto-ph-100-z-155-c110-1-290-spray-100ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-ph-100-z-155-c110-1-290-spray-100ml.jpg" 2>/dev/null

echo "Uploading takemoto-pepi-300-z-155-c110-1-290-spray-300ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-pepi-300-z-155-c110-1-290-spray-300ml.jpg" 2>/dev/null

echo "Uploading takemoto-aom-400-z-155-c110-1-290-spray-400ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-aom-400-z-155-c110-1-290-spray-400ml.jpg" 2>/dev/null

echo "Uploading takemoto-aom-300-z-155-c110-1-290-spray-300ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-aom-300-z-155-c110-1-290-spray-300ml.jpg" 2>/dev/null

echo "Uploading takemoto-aom-200-z-155-c110-1-290-spray-200ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-aom-200-z-155-c110-1-290-spray-200ml.jpg" 2>/dev/null

echo "Uploading takemoto-ambe-300-z-155-c110-1-290-spray-300ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-ambe-300-z-155-c110-1-290-spray-300ml.jpg" 2>/dev/null

echo "Uploading takemoto-ambe-200-z-155-c110-1-290-spray-200ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-ambe-200-z-155-c110-1-290-spray-200ml.jpg" 2>/dev/null

echo "Uploading takemoto-ambe-150-z-155-c110-1-290-spray-150ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-ambe-150-z-155-c110-1-290-spray-150ml.jpg" 2>/dev/null

echo "Uploading takemoto-supi-300-z-155-c110-1-290-spray-300ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-supi-300-z-155-c110-1-290-spray-300ml.jpg" 2>/dev/null

echo "Uploading takemoto-s-pmpin-300-z-155-c110-1-290-spray-300ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-s-pmpin-300-z-155-c110-1-290-spray-300ml.jpg" 2>/dev/null

echo "Uploading takemoto-s-pewin-150a-z-155-c110-1-290-spray-150ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-s-pewin-150a-z-155-c110-1-290-spray-150ml.jpg" 2>/dev/null

echo "Uploading takemoto-s-pewin-120a-z-155-c110-1-290-spray-120ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-s-pewin-120a-z-155-c110-1-290-spray-120ml.jpg" 2>/dev/null

echo "Uploading takemoto-s-pepin-200a-z-155-c110-1-290-spray-200ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-s-pepin-200a-z-155-c110-1-290-spray-200ml.jpg" 2>/dev/null

echo "Uploading takemoto-s-pepin-200-z-155-c110-1-290-spray-200ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-s-pepin-200-z-155-c110-1-290-spray-200ml.jpg" 2>/dev/null

echo "Uploading takemoto-s-pepin-120-z-155-c110-1-290-spray-120ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-s-pepin-120-z-155-c110-1-290-spray-120ml.jpg" 2>/dev/null

echo "Uploading takemoto-s-pepin-100-z-155-c110-1-290-spray-100ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-s-pepin-100-z-155-c110-1-290-spray-100ml.jpg" 2>/dev/null

echo "Uploading takemoto-s-pemin-200a-z-155-c110-1-290-spray-200ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-s-pemin-200a-z-155-c110-1-290-spray-200ml.jpg" 2>/dev/null

echo "Uploading takemoto-s-pemin-200-z-155-c110-1-290-spray-200ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-s-pemin-200-z-155-c110-1-290-spray-200ml.jpg" 2>/dev/null

echo "Uploading takemoto-s-pemin-120-z-155-c110-1-290-spray-120ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-s-pemin-120-z-155-c110-1-290-spray-120ml.jpg" 2>/dev/null

echo "Uploading takemoto-s-pemin-100-z-155-c110-1-290-spray-100ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-s-pemin-100-z-155-c110-1-290-spray-100ml.jpg" 2>/dev/null

echo "Uploading takemoto-s-opt-150b-z-155-c110-1-290-spray-150ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-s-opt-150b-z-155-c110-1-290-spray-150ml.jpg" 2>/dev/null

echo "Uploading takemoto-s-apin-300-z-155-c110-1-290-spray-300ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-s-apin-300-z-155-c110-1-290-spray-300ml.jpg" 2>/dev/null

echo "Uploading takemoto-s-apin-100-z-155-c110-1-290-spray-100ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-s-apin-100-z-155-c110-1-290-spray-100ml.jpg" 2>/dev/null

echo "Uploading takemoto-s-aompn-300-z-155-c110-1-290-spray-300ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-s-aompn-300-z-155-c110-1-290-spray-300ml.jpg" 2>/dev/null

echo "Uploading takemoto-ph-50iii-z-155-c110-1-290-spray-50ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-ph-50iii-z-155-c110-1-290-spray-50ml.jpg" 2>/dev/null

echo "Uploading takemoto-ph-500-z-155-c110-1-290-spray-500ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-ph-500-z-155-c110-1-290-spray-500ml.jpg" 2>/dev/null

echo "Uploading takemoto-ph-400-z-155-c110-1-290-spray-400ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-ph-400-z-155-c110-1-290-spray-400ml.jpg" 2>/dev/null

echo "Uploading takemoto-ph-300-z-155-c110-1-290-spray-300ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-ph-300-z-155-c110-1-290-spray-300ml.jpg" 2>/dev/null

echo "Uploading takemoto-ph-250-z-155-c110-1-290-spray-250ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-ph-250-z-155-c110-1-290-spray-250ml.jpg" 2>/dev/null

echo "Uploading takemoto-ph-200-z-155-c110-1-290-spray-200ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-ph-200-z-155-c110-1-290-spray-200ml.jpg" 2>/dev/null

echo "Uploading takemoto-ph-150-z-155-c110-1-290-spray-150ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-ph-150-z-155-c110-1-290-spray-150ml.jpg" 2>/dev/null

echo "Uploading takemoto-supi-300-z-155-c112-2-spray-300ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-supi-300-z-155-c112-2-spray-300ml.jpg" 2>/dev/null

echo "Uploading takemoto-s-pmpin-300-z-155-c112-2-spray-300ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-s-pmpin-300-z-155-c112-2-spray-300ml.jpg" 2>/dev/null

echo "Uploading takemoto-s-pewin-150a-z-155-c112-2-spray-150ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-s-pewin-150a-z-155-c112-2-spray-150ml.jpg" 2>/dev/null

echo "Uploading takemoto-s-pewin-120a-z-155-c112-2-spray-120ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-s-pewin-120a-z-155-c112-2-spray-120ml.jpg" 2>/dev/null

echo "Uploading takemoto-s-pepin-200a-z-155-c112-2-spray-200ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-s-pepin-200a-z-155-c112-2-spray-200ml.jpg" 2>/dev/null

echo "Uploading takemoto-s-pepin-200-z-155-c112-2-spray-200ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-s-pepin-200-z-155-c112-2-spray-200ml.jpg" 2>/dev/null

echo "Uploading takemoto-s-pepin-120-z-155-c112-2-spray-120ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-s-pepin-120-z-155-c112-2-spray-120ml.jpg" 2>/dev/null

echo "Uploading takemoto-s-pepin-100-z-155-c112-2-spray-100ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-s-pepin-100-z-155-c112-2-spray-100ml.jpg" 2>/dev/null

echo "Uploading takemoto-s-pemin-200a-z-155-c112-2-spray-200ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-s-pemin-200a-z-155-c112-2-spray-200ml.jpg" 2>/dev/null

echo "Uploading takemoto-s-pemin-200-z-155-c112-2-spray-200ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-s-pemin-200-z-155-c112-2-spray-200ml.jpg" 2>/dev/null

echo "Uploading takemoto-s-pemin-120-z-155-c112-2-spray-120ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-s-pemin-120-z-155-c112-2-spray-120ml.jpg" 2>/dev/null

echo "Uploading takemoto-s-pemin-100-z-155-c112-2-spray-100ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-s-pemin-100-z-155-c112-2-spray-100ml.jpg" 2>/dev/null

echo "Uploading takemoto-s-opt-150b-z-155-c112-2-spray-150ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-s-opt-150b-z-155-c112-2-spray-150ml.jpg" 2>/dev/null

echo "Uploading takemoto-s-apin-300-z-155-c112-2-spray-300ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-s-apin-300-z-155-c112-2-spray-300ml.jpg" 2>/dev/null

echo "Uploading takemoto-s-apin-100-z-155-c112-2-spray-100ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-s-apin-100-z-155-c112-2-spray-100ml.jpg" 2>/dev/null

echo "Uploading takemoto-s-aompn-300-z-155-c112-2-spray-300ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-s-aompn-300-z-155-c112-2-spray-300ml.jpg" 2>/dev/null

echo "Uploading takemoto-ph-50iii-z-155-c112-2-spray-50ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-ph-50iii-z-155-c112-2-spray-50ml.jpg" 2>/dev/null

echo "Uploading takemoto-ph-500-z-155-c112-2-spray-500ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-ph-500-z-155-c112-2-spray-500ml.jpg" 2>/dev/null

echo "Uploading takemoto-ph-400-z-155-c112-2-spray-400ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-ph-400-z-155-c112-2-spray-400ml.jpg" 2>/dev/null

echo "Uploading takemoto-ph-300-z-155-c112-2-spray-300ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-ph-300-z-155-c112-2-spray-300ml.jpg" 2>/dev/null

echo "Uploading takemoto-ph-250-z-155-c112-2-spray-250ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-ph-250-z-155-c112-2-spray-250ml.jpg" 2>/dev/null

echo "Uploading takemoto-ph-200-z-155-c112-2-spray-200ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-ph-200-z-155-c112-2-spray-200ml.jpg" 2>/dev/null

echo "Uploading takemoto-ph-150-z-155-c112-2-spray-150ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-ph-150-z-155-c112-2-spray-150ml.jpg" 2>/dev/null

echo "Uploading takemoto-ph-100-z-155-c112-2-spray-100ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-ph-100-z-155-c112-2-spray-100ml.jpg" 2>/dev/null

echo "Uploading takemoto-pepi-300-z-155-c112-2-spray-300ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-pepi-300-z-155-c112-2-spray-300ml.jpg" 2>/dev/null

echo "Uploading takemoto-aom-400-z-155-c112-2-spray-400ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-aom-400-z-155-c112-2-spray-400ml.jpg" 2>/dev/null

echo "Uploading takemoto-aom-300-z-155-c112-2-spray-300ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-aom-300-z-155-c112-2-spray-300ml.jpg" 2>/dev/null

echo "Uploading takemoto-aom-200-z-155-c112-2-spray-200ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-aom-200-z-155-c112-2-spray-200ml.jpg" 2>/dev/null

echo "Uploading takemoto-ambe-300-z-155-c112-2-spray-300ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-ambe-300-z-155-c112-2-spray-300ml.jpg" 2>/dev/null

echo "Uploading takemoto-ambe-200-z-155-c112-2-spray-200ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-ambe-200-z-155-c112-2-spray-200ml.jpg" 2>/dev/null

echo "Uploading takemoto-ambe-150-z-155-c112-2-spray-150ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-ambe-150-z-155-c112-2-spray-150ml.jpg" 2>/dev/null

echo "Uploading takemoto-ph-sw30-pd-0220-pps-pump-pd-0220-over-cap-m-220ml.jpg..."
# shopify theme push --store $STORE --only "assets/takemoto-ph-sw30-pd-0220-pps-pump-pd-0220-over-cap-m-220ml.jpg" 2>/dev/null

echo "Upload complete!"